apiVersion: v1
kind: Service
metadata:
  name: gabrieldossantos-app-service
spec:
  type: NodePort
  selector:
    app: gabrieldossantos-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31000